version: 2

build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.11'

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: psycopg
      extra_requirements:
        - docs
    - method: pip
      path: psycopg_pool
